### ISSUE TITLE
requirements install failed for me

### ISSUE THREAD

**Issue by mowliv** [acmeyer/GPTSummarization#1]
This project is a nice concept and the code looks v. readable. Thanks for posting it.

I got this when I tried to install requirements:

```
$ pip install -r requirements.txt 
Collecting openai
  Downloading openai-0.27.4-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 1.9 MB/s 
Collecting tiktoken
  Downloading tiktoken-0.3.3.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting unstructured
  Downloading unstructured-0.6.1.tar.gz (1.3 MB)
     |████████████████████████████████| 1.3 MB 2.9 MB/s 
Collecting python-dotenv
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git@072713649a9b0069c10aad1aaab819112e8f1e2e
  Cloning https://github.com/facebookresearch/detectron2.git (to revision 072713649a9b0069c10aad1aaab819112e8f1e2e) to /private/var/folders/60/hyqtczr14p16zj8znzq_jgr00000gp/T/pip-install-021_kp3y/detectron2
  Running command git clone -q https://github.com/facebookresearch/detectron2.git /private/var/folders/60/hyqtczr14p16zj8znzq_jgr00000gp/T/pip-install-021_kp3y/detectron2
  Running command git checkout -q 072713649a9b0069c10aad1aaab819112e8f1e2e
    ERROR: Command errored out with exit status 1:
     command: /Users/Michael/.pyenv/versions/3.8.5/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/60/hyqtczr14p16zj8znzq_jgr00000gp/T/pip-install-021_kp3y/detectron2/setup.py'"'"'; __file__='"'"'/private/var/folders/60/hyqtczr14p16zj8znzq_jgr00000gp/T/pip-install-021_kp3y/detectron2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/60/hyqtczr14p16zj8znzq_jgr00000gp/T/pip-pip-egg-info-py4599a0
         cwd: /private/var/folders/60/hyqtczr14p16zj8znzq_jgr00000gp/T/pip-install-021_kp3y/detectron2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/60/hyqtczr14p16zj8znzq_jgr00000gp/T/pip-install-021_kp3y/detectron2/setup.py", line 10, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by acmeyer** [comment]
Hmmm, you're right, seems like they made some changes and that branch is no longer around. The good news is that you don't need detectron2 to run it, it'll just fall back to a different process. I updated it to just pull from the main repo, let me know if that works for you, seems to be working okay for me.

**Comment by mowliv** [comment]
I got the same error. Did you push your commit?

**Comment by acmeyer** [comment]
I did but I also just removed it completely as it is unnecessary and seems to be giving issues.
